CREATE TABLE IF NOT EXISTS jobtracker.article_accessories (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  accessory VARCHAR(150) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;
